
require("dotenv").config();
const express=require("express"),cors=require("cors"),crypto=require("crypto");const{Pool}=require("pg");
const app=express();app.use(cors());app.use(express.json());app.use(express.static("public"));
const PORT=process.env.PORT||10000,BOT_TOKEN=process.env.BOT_TOKEN||"",ADMIN_KEY=process.env.ADMIN_KEY||"spacenovax-admin";
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}}):null;
const memory={users:new Map(),claims:[],totalMined:0};
const PHASES=[{name:"Genesis Launch",cap:500000000,reward:30},{name:"Lunar Mission",cap:1000000000,reward:15},{name:"Orbital Expansion",cap:1500000000,reward:7.5},{name:"Deep Space",cap:2000000000,reward:3.75},{name:"Interstellar",cap:3000000000,reward:1.875}];
const MISSIONS=[
{id:"daily",icon:"✅",title:"Daily Check-in",reward:20,url:"#",type:"instant"},
{id:"website",icon:"🌐",title:"Visit Website",reward:100,url:process.env.WEBSITE_URL||"https://spacenovax.com",type:"instant"},
{id:"telegram_channel",icon:"✈️",title:"Join Telegram Channel",reward:200,url:process.env.TELEGRAM_CHANNEL_URL||"https://t.me/spacenovaxteam",type:"admin_review"},
{id:"telegram_group",icon:"💬",title:"Join Telegram Group",reward:200,url:process.env.TELEGRAM_GROUP_URL||"https://t.me/spacesnovax",type:"admin_review"},
{id:"youtube",icon:"▶️",title:"Subscribe YouTube",reward:300,url:process.env.YOUTUBE_URL||"https://youtube.com/@spacenovaxteam",type:"admin_review"},
{id:"x_follow",icon:"𝕏",title:"Follow on X",reward:300,url:process.env.X_URL||"https://x.com/spacenovaxteam",type:"admin_review"},
{id:"discord",icon:"👾",title:"Join Discord",reward:300,url:process.env.DISCORD_URL||"https://discord.gg/rxVNWMC8e8",type:"admin_review"},
{id:"invite",icon:"👥",title:"Invite 1 Friend",reward:500,url:"#",type:"admin_review"}
];
function phaseFor(t){return PHASES.find(p=>t<p.cap)||PHASES[PHASES.length-1]}function levelFromExp(x){return Math.min(20,Math.max(1,Math.floor(Number(x||0)/1000)+1))}function levelBonus(l){if(l>=20)return 1;if(l>=10)return .5;if(l>=5)return .2;return Math.max(0,(l-1)*.05)}function referralBonus(r){if(r>=500)return .5;if(r>=100)return .3;if(r>=50)return .2;if(r>=20)return .1;if(r>=5)return .05;return 0}function dailyReward(u,p){return p.reward*(1+levelBonus(Number(u.level||1))+referralBonus(Number(u.referrals||0)))}
function verify(initData){if(!BOT_TOKEN||!initData)return{ok:false};const params=new URLSearchParams(initData),hash=params.get("hash");if(!hash)return{ok:false};params.delete("hash");const str=[...params.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n");const key=crypto.createHmac("sha256","WebAppData").update(BOT_TOKEN).digest();const calc=crypto.createHmac("sha256",key).update(str).digest("hex");return{ok:calc===hash}}
function readUser(req){const initData=req.headers["x-telegram-init-data"]||req.body.initData||"";let tg={id:"demo-user",username:"demo",first_name:"Space Explorer"};if(initData){try{const u=JSON.parse(new URLSearchParams(initData).get("user")||"{}");if(u.id)tg=u}catch{}}return{tg,initData}}
async function initDb(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS users(telegram_id TEXT PRIMARY KEY,username TEXT,first_name TEXT,balance NUMERIC DEFAULT 0,exp NUMERIC DEFAULT 0,level INTEGER DEFAULT 1,referrals INTEGER DEFAULT 0,wallet TEXT DEFAULT '',mining_start BIGINT,last_checkin TEXT DEFAULT '',created_at TIMESTAMP DEFAULT NOW(),updated_at TIMESTAMP DEFAULT NOW())`);await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS exp NUMERIC DEFAULT 0`);await pool.query(`CREATE TABLE IF NOT EXISTS mission_claims(id SERIAL PRIMARY KEY,telegram_id TEXT,mission_id TEXT,status TEXT DEFAULT 'pending',reward NUMERIC DEFAULT 0,created_at TIMESTAMP DEFAULT NOW(),reviewed_at TIMESTAMP,UNIQUE(telegram_id,mission_id))`);await pool.query(`CREATE TABLE IF NOT EXISTS stats(key TEXT PRIMARY KEY,value NUMERIC DEFAULT 0)`);await pool.query(`INSERT INTO stats(key,value) VALUES('total_mined',0) ON CONFLICT(key) DO NOTHING`)}
async function totalMined(){if(!pool)return memory.totalMined;const r=await pool.query(`SELECT value FROM stats WHERE key='total_mined'`);return Number(r.rows[0]?.value||0)}async function addMined(n){if(!pool){memory.totalMined+=Number(n);return memory.totalMined}const r=await pool.query(`UPDATE stats SET value=value+$1 WHERE key='total_mined' RETURNING value`,[n]);return Number(r.rows[0].value)}
async function getUser(tg){const id=String(tg.id||"demo-user");if(!pool){if(!memory.users.has(id))memory.users.set(id,{telegram_id:id,username:tg.username||"demo",first_name:tg.first_name||"Space Explorer",balance:15250,exp:6850,level:7,referrals:128,wallet:"",mining_start:null,last_checkin:""});return memory.users.get(id)}const e=await pool.query(`SELECT * FROM users WHERE telegram_id=$1`,[id]);if(e.rows[0])return e.rows[0];const c=await pool.query(`INSERT INTO users(telegram_id,username,first_name,balance,exp,level,referrals) VALUES($1,$2,$3,0,0,1,0) RETURNING *`,[id,tg.username||"",tg.first_name||""]);return c.rows[0]}
async function saveUser(u){u.level=levelFromExp(u.exp||0);if(!pool){memory.users.set(String(u.telegram_id),u);return u}const r=await pool.query(`UPDATE users SET balance=$2,exp=$3,level=$4,referrals=$5,wallet=$6,mining_start=$7,last_checkin=$8,updated_at=NOW() WHERE telegram_id=$1 RETURNING *`,[u.telegram_id,u.balance,u.exp||0,u.level,u.referrals,u.wallet||"",u.mining_start,u.last_checkin||""]);return r.rows[0]}
async function doneMissions(id){if(!pool)return memory.claims.filter(c=>c.telegram_id===id&&c.status==="approved").map(c=>c.mission_id);const r=await pool.query(`SELECT mission_id FROM mission_claims WHERE telegram_id=$1 AND status='approved'`,[id]);return r.rows.map(x=>x.mission_id)}
app.get("/api/health",(req,res)=>res.json({ok:true,service:"SpaceNovaX v35 Meteor SPNX Polish UI",mode:pool?"postgres":"memory"}));
app.post("/api/me",async(req,res)=>{try{const{tg,initData}=readUser(req);if(process.env.SKIP_TELEGRAM_VERIFY!=="true"&&BOT_TOKEN&&initData&&!verify(initData).ok)return res.status(401).json({ok:false,error:"Invalid Telegram signature"});const u=await getUser(tg),tm=await totalMined(),ph=phaseFor(tm);res.json({ok:true,user:u,phase:ph,totalMined:tm,dailyReward:dailyReward(u,ph),missions:MISSIONS,completedMissions:await doneMissions(String(u.telegram_id)),phases:PHASES})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post("/api/mine/start",async(req,res)=>{try{const u=await getUser(readUser(req).tg);if(!u.mining_start){u.mining_start=Date.now();await saveUser(u)}res.json({ok:true,user:u})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post("/api/mine/claim",async(req,res)=>{try{const u=await getUser(readUser(req).tg);if(!u.mining_start)return res.json({ok:false,error:"Mining has not started"});const elapsed=Date.now()-Number(u.mining_start);if(elapsed<86400000)return res.json({ok:false,error:"Mining session is not complete",remainingMs:86400000-elapsed});const tm=await totalMined(),ph=phaseFor(tm),rew=dailyReward(u,ph);u.balance=Number(u.balance)+rew;u.exp=Number(u.exp||0)+100;u.mining_start=null;const nt=await addMined(rew);await saveUser(u);res.json({ok:true,reward:rew,user:u,totalMined:nt,phase:phaseFor(nt)})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post("/api/checkin",async(req,res)=>{try{const u=await getUser(readUser(req).tg);const today=new Date().toISOString().slice(0,10);if(u.last_checkin===today)return res.json({ok:false,error:"Already checked in today"});u.balance=Number(u.balance)+20;u.exp=Number(u.exp||0)+25;u.last_checkin=today;await saveUser(u);res.json({ok:true,reward:20,user:u})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post("/api/wallet",async(req,res)=>{try{const u=await getUser(readUser(req).tg);u.wallet=String(req.body.wallet||"").trim();await saveUser(u);res.json({ok:true,user:u})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post("/api/mission/claim",async(req,res)=>{try{const u=await getUser(readUser(req).tg);const m=MISSIONS.find(x=>x.id===req.body.missionId);if(!m)return res.status(404).json({ok:false,error:"Mission not found"});if(m.id==="daily")return res.redirect(307,"/api/checkin");const id=String(u.telegram_id);if(!pool){let ex=memory.claims.find(c=>c.telegram_id===id&&c.mission_id===m.id);if(ex)return res.json({ok:true,status:ex.status,claim:ex,user:u});const c={telegram_id:id,mission_id:m.id,status:m.type==="instant"?"approved":"pending",reward:m.reward,created_at:new Date().toISOString()};memory.claims.push(c);if(c.status==="approved"){u.balance=Number(u.balance)+m.reward;u.exp=Number(u.exp||0)+50;await saveUser(u)}return res.json({ok:true,status:c.status,claim:c,user:u})}const ex=await pool.query(`SELECT * FROM mission_claims WHERE telegram_id=$1 AND mission_id=$2`,[id,m.id]);if(ex.rows[0])return res.json({ok:true,status:ex.rows[0].status,claim:ex.rows[0],user:u});const st=m.type==="instant"?"approved":"pending";const q=await pool.query(`INSERT INTO mission_claims(telegram_id,mission_id,status,reward) VALUES($1,$2,$3,$4) RETURNING *`,[id,m.id,st,m.reward]);if(st==="approved")await pool.query(`UPDATE users SET balance=balance+$1,exp=exp+50 WHERE telegram_id=$2`,[m.reward,id]);res.json({ok:true,status:q.rows[0].status,claim:q.rows[0],user:await getUser(readUser(req).tg)})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.get("/api/admin/stats",async(req,res)=>{if(req.headers["x-admin-key"]!==ADMIN_KEY)return res.status(401).json({ok:false});const tm=await totalMined();if(!pool){const users=[...memory.users.values()].sort((a,b)=>Number(b.balance)-Number(a.balance));return res.json({ok:true,totalUsers:users.length,totalMined:tm,phase:phaseFor(tm),users,claims:memory.claims})}const count=await pool.query(`SELECT COUNT(*)::int AS count FROM users`);const users=await pool.query(`SELECT * FROM users ORDER BY balance DESC LIMIT 100`);const claims=await pool.query(`SELECT * FROM mission_claims ORDER BY created_at DESC LIMIT 100`);res.json({ok:true,totalUsers:count.rows[0].count,totalMined:tm,phase:phaseFor(tm),users:users.rows,claims:claims.rows})});
app.post("/api/admin/mission/review",async(req,res)=>{if(req.headers["x-admin-key"]!==ADMIN_KEY)return res.status(401).json({ok:false});const{claimId,status}=req.body;if(!["approved","rejected"].includes(status))return res.json({ok:false});if(!pool){const c=memory.claims[Number(claimId)];if(!c)return res.json({ok:false});if(c.status!=="approved"&&status==="approved"){const u=memory.users.get(c.telegram_id);if(u){u.balance=Number(u.balance)+Number(c.reward);u.exp=Number(u.exp||0)+50;memory.users.set(c.telegram_id,u)}}c.status=status;return res.json({ok:true,claim:c})}const b=await pool.query(`SELECT * FROM mission_claims WHERE id=$1`,[claimId]);if(!b.rows[0])return res.json({ok:false});const c=b.rows[0];if(c.status!=="approved"&&status==="approved")await pool.query(`UPDATE users SET balance=balance+$1,exp=exp+50 WHERE telegram_id=$2`,[c.reward,c.telegram_id]);const r=await pool.query(`UPDATE mission_claims SET status=$2,reviewed_at=NOW() WHERE id=$1 RETURNING *`,[claimId,status]);res.json({ok:true,claim:r.rows[0]})});
app.post("/api/admin/user/adjust",async(req,res)=>{if(req.headers["x-admin-key"]!==ADMIN_KEY)return res.status(401).json({ok:false});const{telegramId,amount}=req.body,n=Number(amount||0);if(!telegramId||!Number.isFinite(n))return res.json({ok:false});if(!pool){const u=memory.users.get(String(telegramId));if(!u)return res.json({ok:false});u.balance=Number(u.balance)+n;memory.users.set(String(telegramId),u);return res.json({ok:true,user:u})}const r=await pool.query(`UPDATE users SET balance=balance+$1 WHERE telegram_id=$2 RETURNING *`,[n,String(telegramId)]);res.json({ok:true,user:r.rows[0]})});
initDb().then(()=>app.listen(PORT,()=>console.log(`SpaceNovaX v35 Meteor SPNX Polish UI`))).catch(e=>{console.error(e);process.exit(1)});
